Capston
yohannesdagnachew/Visit-Ethiopia pull request #1
Opened 2022-05-19 13:33 UTC by yohannesdagnachew

### Description
- Personalize the content of your page ✅ 
- Follow these design guidelines ✅ 
- Use a CSS framework  ✅ 
- Creat responsive ✅ 
- Dynamic page ✅ 
- Home page has a link in the menu to the about page. ✅ 
- The mobile menu has a close (X) button that closes the menu. ✅ 
- Featured speakers has be created dynamically in JavaScript. ✅ 

https://github.com/yohannesdagnachew/Visit-Ethiopia/pull/1#issue-1241786048

2022-05-19 16:17 UTC, OLIPLICHE requested changes
Hi @yohannesdagnachew , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- Linter is green (the last commit have a green check mark (✅)) 👏
- README file is descriptive 👏
- Commit messages are meaningful 👏 👏
- Github flow is correctly used (Pull Request is made from the feature branch into the main branch) 👏
- Pull Request is descriptive 👏

## Required Changes ♻️

- [ ] Please make sure the video presentation contains a demo of the project, showing the pages in different screen sizes.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-19 16:17 UTC, OLIPLICHE commented on README.md
>  - etc
- [ ] Please make sure the README contains an "Acknowledgements" section or similar that gives appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

2022-05-19 16:17 UTC, OLIPLICHE commented on index.html
> +    </div>
- [ ] Please add social media links to this top bar because you need to follow the original design. ([see project](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015))

2022-05-19 16:17 UTC, OLIPLICHE commented on index.html
> +      </nav>
- [ ] Please make sure this bar is in white color ([follow design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015))

2022-05-19 16:17 UTC, OLIPLICHE commented on index.html
> +      </section>
- [ ] Please make sure the logo is aligned to the left and the text to the right

2022-05-19 16:17 UTC, OLIPLICHE commented on index.html
> +          <div class="collapse navbar-collapse" id="navbarSupportedContent">
- [ ] Mobile size:
- Please make sure It's possible to navigate between the pages, there's a link from `Home` page to `About` page and the opposite too
-
![t1](https://user-images.githubusercontent.com/63972670/169336754-5bc523d6-51e6-4c7d-b1ac-5447bc425d79.JPG)
 

- Please the footer of the mobile size is in white color.

2022-05-19 16:17 UTC, OLIPLICHE commented on index.html
> +           <h2 class="minster">Year Round</h2>
- [ ] Please move this text on top of "VISIT ETHIOPIA LAND OF ORIGINS" as you see it in the original design. ([see project](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015))

2022-05-19 16:17 UTC, OLIPLICHE commented on index.html
> +          <h3 class="place">PLACES TO VISIT</h3>
- [ ] Please add a divider line as seen in the picture below.
- [ ] Please the articles are five, kindly add one missing. 
![t2](https://user-images.githubusercontent.com/63972670/169343521-8aaebaef-110b-4d08-b284-3a2f18ceb370.JPG)

2022-05-19 16:17 UTC, OLIPLICHE commented on index.html
> +        <h3 class="place2">TOURISTS ABOUT ETHIOPIA</h3>
- [ ] Please a divider line below "TOURISTS ABOUT ETHIOPIA"

2022-05-19 16:17 UTC, OLIPLICHE commented on about.html
> +        </section>
- [ ] Please make sure this section is centered.

2022-05-20 10:22 UTC, CollinsTatang approved these changes
Hi @yohannesdagnachew, 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![image](https://user-images.githubusercontent.com/55596970/158098698-83b2f72b-ec7f-42a8-92dd-1814eb6c8a62.png)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-05-20 10:46 UTC, merged